Friend Module StatisticTypes
    Friend Const AttackDice = "AttackDice"
    Friend Const CellColumn = "CellColumn"
    Friend Const CellRow = "CellRow"
    Friend Const DefendDice = "DefendDice"
    Friend Const Health = "Health"
    Friend Const ItemCount = "ItemCount"
    Friend Const MapId = "MapId"
    Friend Const MaximumAttack = "MaximumAttack"
    Friend Const MaximumDefend = "MaximumDefend"
    Friend Const MaximumHealth = "MaximumHealth"
    Friend Const Peril = "Peril"
    Friend Const XP = "XP"
    Friend Const XPGoal = "XPGoal"
    Friend Const XPLevel = "XPLevel"
End Module
