Friend Module StatisticTypes
    Friend Const Energy = "Energy"
    Friend Const ForageRemaining = "ForageRemaining"
    Friend Const Health = "Health"
    Friend Const ItemCount = "ItemCount"
    Friend Const MapId = "MapId"
    Friend Const MaximumAttack = "MaximumAttack"
    Friend Const MaximumDefend = "MaximumDefend"
    Friend Const MaximumEnergy = "MaximumEnergy"
    Friend Const MaximumHealth = "MaximumHealth"
    Friend Const Peril = "Peril"
    Friend Const Price = "Price"
    Friend Const XP = "XP"
    Friend Const XPGoal = "XPGoal"
    Friend Const XPLevel = "XPLevel"
    Friend Const Jools = "Jools"
    Friend Const AdvancementPoints = "AdvancementPoints"
    Friend Const AdvancementPointsPerLevel = "AdvancementPointsPerLevel"
    Friend Const Durability = "Durability"
    Friend Const MaximumDurability = "MaximumDurability"
End Module
