Friend Module TriggerTypes
    Friend Const DruidAllergies = "DruidAllergies"
    Friend Const DruidTeachMenu = "DruidTeachMenu"
    Friend Const ExitDialog = "ExitDialog"
    Friend Const Heal = "Heal"
    Friend Const LearnForaging = "LearnForaging"
    Friend Const LearnTwineMaking = "LearnTwineMaking"
    Friend Const Message = "Message"
    Friend Const NihilistPrices = "NihilistPrices"
    Friend Const Teleport = "Teleport"
    Friend Const TrainHealth = "TrainHealth"
    Friend Const HealerTalk = "HealerTalk"
    Friend Const HealthTrainerTalk = "HealthTrainerTalk"
    Friend Const DruidTalk = "HealthTrainerTalk"
End Module
