Friend Module TriggerTypes
    Friend Const Buy = "Buy"
    Friend Const DruidAllergies = "DruidAllergies"
    Friend Const DruidPrices = "DruidPrices"
    Friend Const DruidTalk = "DruidTalk"
    Friend Const DruidTeachMenu = "DruidTeachMenu"
    Friend Const EnergyTrainerTalk = "EnergyTrainerTalk"
    Friend Const ExitDialog = "ExitDialog"
    Friend Const GorachanTalk = "GorachanTalk"
    Friend Const Heal = "Heal"
    Friend Const HealerPrices = "NihilistPrices"
    Friend Const HealerTalk = "HealerTalk"
    Friend Const HealthTrainerTalk = "HealthTrainerTalk"
    Friend Const LearnForaging = "LearnForaging"
    Friend Const LearnTwineMaking = "LearnTwineMaking"
    Friend Const Message = "Message"
    Friend Const PayInnkeeper = "PayInnkeeper"
    Friend Const PervertInnkeeper = "PervertInnkeeper"
    Friend Const SleepAtInn = "SleepAtInn"
    Friend Const Teleport = "Teleport"
    Friend Const TrainEnergy = "TrainEnergy"
    Friend Const TrainHealth = "TrainHealth"
    Friend Const StartRatQuest = "StartRatQuest"
    Friend Const AcceptRatQuest = "AcceptRatQuest"
    Friend Const EnterCellar = "EnterCellar"
End Module
