Friend Module FlagTypes
    Friend Const AllowFireBuilding = "AllowFireBuilding"
    Friend Const CampingAllowed = "CampingAllowed"
    Friend Const CanCraftTorch = "CanCraftTorch"
    Friend Const IsArmor = "IsArmor"
    Friend Const IsCuttingTool = "IsCuttingTool"
    Friend Const IsWeapon = "IsWeapon"
    Friend Const KnowsFireMaking = "KnowsFireMaking"
    Friend Const KnowsForaging = "KnowsForaging"
    Friend Const KnowsTwineMaking = "KnowsTwineMaking"
    Friend Const KnowsKnapping = "KnowsRockSharpening"
    Friend Const KnowsTorchMaking = "KnowsTorchMaking"
    Friend Const LearnByDoing = "LearnByDoing"
    Friend Const PaidInnkeeper = "PaidInnkeeper"
    Friend Const RatQuest = "RatQuest"
End Module
