Public Module Constants
    Public Const DefaultScreenWidth = ViewWidth * 3
    Public Const DefaultScreenHeight = ViewHeight * 3
    Public Const BagelQuestFont = "BagelQuestFont"
    Public Const ViewHeight = 216
    Public Const ViewWidth = 384
    Public Const GameTitle = "Bagel Quest"

    Friend Const ConfigFileName = "config.json"
    Friend Const ActionsText = "Actions"
    Friend Const AttackText = "Attack!"
    Friend Const BuildFireText = "Build Fire"
    Friend Const BuildFurnaceText = "Build Furnace"
    Friend Const CancelText = "Cancel"
    Friend Const CookBagelText = "Cook Bagel"
    Friend Const ContinueText = "Continue"
    Friend Const CraftText = "Craft..."
    Friend Const DropAllText = "Drop All"
    Friend Const DropHalfText = "Drop Half"
    Friend Const DropOneText = "Drop One"
    Friend Const EquipText = "Equip"
    Friend Const EquipmentText = "Equipment"
    Friend Const ForageText = "Forage..."
    Friend Const GameMenuText = "Game Menu"
    Friend Const GroundText = "Ground..."
    Friend Const InventoryText = "Inventory"
    Friend Const KnapText = "Knap"
    Friend Const MainMenuText = "Main Menu"
    Friend Const MakeHatchetText = "Make Hatchet"
    Friend Const MakeTorchText = "Make Torch"
    Friend Const MakeTwineText = "Make Twine"
    Friend Const OnTheGroundText = "On the Ground"
    Friend Const PlaceholderText = "<placeholder>"
    Friend Const PutOutFireText = "Put Out Fire"
    Friend Const RunText = "Run!"
    Friend Const SelectText = "Select"
    Friend Const SleepText = "Sleep"
    Friend Const StatisticsText = "Statistics"
    Friend Const TakeAllText = "Take All"
    Friend Const TakeHalfText = "Take Half"
    Friend Const TakeOneText = "Take One"
    Friend Const UnequipText = "Unequip"
    Friend Const YerDeadText = "Yer dead!"
    Friend Const YouWinText = "You Win!"

    Friend Const CellHeight = 16
    Friend Const CellWidth = 16
    Private Const CenterX = ViewWidth \ 2
    Private Const CenterY = ViewHeight \ 2
    Friend Const CenterCellX = CenterX - CellWidth \ 2
    Friend Const CenterCellY = CenterY - CellHeight \ 2
    Friend Const LeftColumn = -((CenterCellX + CellWidth - 1) \ CellWidth)
    Private Const RightColumn = (ViewWidth - CenterCellX + CellWidth - 1) \ CellWidth
    Private Const BottomRow = (ViewHeight - CenterCellY + CellHeight - 1) \ CellHeight
    Friend Const TopRow = -((CenterCellY + CellHeight - 1) \ CellHeight)
    Friend Const MapRenderX = CenterCellX + LeftColumn * CellWidth
    Friend Const MapRenderY = CenterCellY + TopRow * CellHeight
    Friend Const MapRenderColumns = RightColumn - LeftColumn
    Friend Const MapRenderRows = BottomRow - TopRow
End Module
