Friend Module GameState
    Friend Const ActionMenu = "ActionMenu"
    Friend Const Combat = "Combat"
    Friend Const Dead = "Dead"
    Friend Const Drop = "Drop"
    Friend Const Forage = "Forage"
    Friend Const Ground = "Ground"
    Friend Const GroundDetail = "GroudDetail"
    Friend Const Inventory = "Inventory"
    Friend Const InventoryDetail = "InventoryDetail"
    Friend Const Message = "Message"
    Friend Const MoveDown = "MoveDown"
    Friend Const MoveLeft = "MoveLeft"
    Friend Const MoveRight = "MoveRight"
    Friend Const MoveUp = "MoveUp"
    Friend Const Navigation = "Navigation"
    Friend Const Run = "Run"
    Friend Const Statistics = "Statistics"
    Friend Const Take = "Take"
End Module
